apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
# Example: <ha/basic>-<dbs/dos>-<lh/ebs>
    name: ha-dbs-lh
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"             # Number of copies to keep
  staleReplicaTimeout: "30"         # Time in seconds before replica is considered stale
reclaimPolicy: Retain              # Options: Retain or Delete
allowVolumeExpansion: true         # Allow PVCs to be resized
volumeBindingMode: Immediate        # Or WaitForFirstConsumer