apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-data
  labels:
    app.kubernetes.io/instance: minio
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/mnt/data-lv-01/minio"
    openebs.io/cas-type: local
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer